- name: variables
  hosts: local
  connection: local
  tasks:
    - name: Print variables
      ansible.builtin.debug:
        msg: "This is Chouda Reddy, how is the part of DevSecOps with AWS Batch"
