- name: variables
  hosts: local
  connection: local
  var:
    NAME: "Chouda Reddy"
    COURSE: "DevSecOps with AWS"
  tasks:
    - name: Print variables
      ansible.builtin.debug:
        msg: "This is {{ NAME }}, how is the part of {{ COURSE }} Batch"
