- name: "variables from files"
  hosts: local
  connection: local
  vars:
    - courses.yaml
  tasks:
    - name: "Vars from Files"
      ansible.builtin.debug:
        msg: "This is {{ NAME }}, who is the part of {{ COURSE }} Batch"
