- name: "Variables Preference Order"
  hosts: local
  connection: local
  vars:
    GREET: Play
  vars_files:
    - courses.yaml
  vars_prompt:
    - name: GREET
      prompt: "Enter the value"
      private: false
  tasks:
    - name: print the variables
      vars:
        GREET: "TASK"
      ansible.builtin.debug:
        msg: "Hello from {{ GREET }}"
