- name: Check that given value is greater than 10 or not.
  hosts: local
  connection: local
  vars:
    my_variable: 11
  tasks:
    - name: Print the given value is greater than 10 or not
      ansible.builtin.debug:
        msg: "Given number {{ my_variable }} is greater than 10"
      when: my_variable > 10
    - name: Print the given value is less than or equal to 10
      ansible.builtin.debug:
        msg: "Given number {{ my_variable }} is less than or equal 10"
      when: my_variable <= 10
