- name: "Installing Packages"
  hosts: web
  become: yes
  tasks:
    - name: "Installing packages"
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "gcc", state: "absent" }
        - { name: "mysql", state: "present" }
        - { name: "git", state: "absent" }
        - { name: "zip", state: "present" }
